name: oytun
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#2f2f2f'
    - '#545454'
    - '#9d9d9d'
    - '#c6c6c6'
  brandStrength: 0.9011650888714939
  lightness: 0.9932197718881071
  saturation: 0.8213066549506038
  rhythmicContrast: 0.39015752100385725
purpose: []
