name: oytun
favicon: null
layout_spectrum: 0.9249523938633502
typography_spectrum: 0.56122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9011650888714939
  lightness: 0.9932197718881071
  saturation: 0.8213066549506038
  rhythmicContrast: 0.39015752100385725
purpose: []
